services:
  node0:
    build: .
    container_name: node0
    hostname: node0
    networks:
      - test-net
    command: ["./user", "8001"]

  node1:
    build: .
    container_name: node1
    hostname: node1
    networks:
      - test-net
    depends_on:
      - node0
    command: ["sh", "-c", "sleep 2 && ./user 8002 node0 8001"]

  node2:
    build: .
    container_name: node2
    hostname: node2
    networks:
      - test-net
    depends_on:
      - node0
      - node1
    command: ["sh", "-c", "sleep 2 && ./user 8003 node0 8001 node1 8002"]

  node3:
    build: .
    container_name: node3
    hostname: node3
    networks:
      - test-net
    depends_on:
      - node1
      - node2
      - node0
    command: ["sh", "-c", "sleep 2 && ./user 8004 node1 8002 node2 8003 node0 8001"]

  node4:
    build: .
    container_name: node4
    hostname: node4
    networks:
      - test-net
    depends_on:
      - node1
      - node0
      - node2
    command: ["sh", "-c", "sleep 3 && ./user 8005 node1 8002 node0 8001 node2 8003"]

  node5:
    build: .
    container_name: node5
    hostname: node5
    networks:
      - test-net
    depends_on:
      - node2
      - node1
      - node4
    command: ["sh", "-c", "sleep 3 && ./user 8006 node2 8003 node1 8002 node4 8005"]

networks:
  test-net:
    driver: bridge
