services:
  user1:
    build: .
    container_name: user1
    networks:
      - test-net
    ports:
      - "8001:8001"
    command: ["./user", "8001"]

  user2:
    build: .
    container_name: user2
    networks:
      - test-net
    ports:
      - "8002:8002"
    depends_on:
      - user1
    command: ["sh", "-c", "sleep 1 && ./user 8002 user1 8001"]

networks:
  test-net:
    driver: bridge
