#include "peer.h"

user_t* direct_peers;
user_data_t* this_peer;
int this_sockfd;
pthread_mutex_t mtx = PTHREAD_MUTEX_INITIALIZER;

void init_peer(user_data_t* peer)
{
	// TODO: Fix hostname, ip_addr to be generated by container num
	peer->user.hostname = "example_hostname";
	peer->user.ip_addr = "10.0.1.5"
	peer->user.port = 0000;
	peer->user.connected = false;
	peer->routing_table = malloc(MAX_DIRECT_PEERS * sizeof(user_t*));
	peer->table_size = MAX_DIRECT_PEERS;
}

/*
 * Resizes the nav_table to add the additional columns, rows based on new_peers
 */
void resize_table(nav_table_t* table, int new_peers)
{
	nav_table_t* new_table = (nav_table_t*)malloc(sizeof(nav_table_t));
}

/*
 * Exchanges routing data between host, user 
 */
void gossip(user_data_t* host, user_data_t* user)
{
}

/*
 * Server thread, handles incoming connections
 */
void* server_thread(void* arg)
{
}

/*
 * Client thread, handles outgoing connections
*/
void* client_thread(void* arg)
{
}

int main(int argc, char** argv)
{
	setbuf(stdout, NULL);
	setbuf(stderr, NULL);

	printf("Good build\n");

	user_data_t* peer_data = malloc(sizeof(user_data_t));

	return 0;
}
